development:
  sessions:
    default:
      database: starlight
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: stargazer_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
